import crypt
import getpass
import itertools

def my_test():
    output = open("dictionary_sorted.txt").read()
    output = output.replace("ü", "u")
    output = output.replace("é", "e")
    output = output.replace("â", "a")
    output = output.replace("ä", "a")
    output = output.replace("à", "a")
    output = output.replace("å", "a")
    output = output.replace("ç", "c")
    output = output.replace("ê", "e")
    output = output.replace("ë", "e")
    output = output.replace("è", "e")
    output = output.replace("ï", "i")
    output = output.replace("î", "i")
    output = output.replace("ì", "i")
    output = output.replace("ô", "o")
    output = output.replace("ö", "o")
    output = output.replace("ò", "o")
    output = output.replace("û", "u")
    output = output.replace("ù", "u")
    output = output.replace("ÿ", "y")
    output = output.replace("á", "a")
    output = output.replace("í", "i")
    output = output.replace("Ÿ", "Y")
    output = output.replace("š", "s")
    output = output.replace("Š", "S")
    output = output.replace("Ñ", "N")
    output = output.replace("ñ", "n")
    output = output.replace("ú", "u")
    output = output.replace("ó", "o")
    output = output.replace("ý", "y")
    output = output.replace("ü", "u")
    output = output.replace("õ", "o")
    output = output.replace("ã", "a")
    output = output.replace("Ý", "Y")
    output = output.replace("Ü", "U")
    output = output.replace("Û", "U")
    output = output.replace("Ú", "U")
    output = output.replace("Ù", "U")
    output = output.replace("Ö", "O")
    output = output.replace("Õ", "O")
    output = output.replace("Ô", "O")
    output = output.replace("Ó", "O")
    output = output.replace("Ò", "O")
    output = output.replace("Ï", "I")
    output = output.replace("Î", "I")
    output = output.replace("Í", "I")
    output = output.replace("Ì", "I")
    output = output.replace("Ë", "E")
    output = output.replace("Ê", "E")
    output = output.replace("É", "E")
    output = output.replace("È", "E")
    output = output.replace("Å", "A")
    output = output.replace("Ä", "A")
    output = output.replace("Ã", "A")
    output = output.replace("Â", "A")
    output = output.replace("Á", "A")
    output = output.replace("À", "A")

    
    f = open("dictionary_sorted.txt", "w")
    f.write(output)
    f.close()


if __name__ == "__main__":
    my_test()
